# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api_schemas.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api_schemas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pi_schemas.proto\x12\x03\x61pi\"U\n\x0fShippingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x13\n\x0bpostal_code\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\"@\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"\xba\x01\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x1d\n\x05items\x18\x04 \x03(\x0b\x32\x0e.api.OrderItem\x12.\n\x10shipping_address\x18\x05 \x01(\x0b\x32\x14.api.ShippingAddress\x12\x16\n\x0epayment_method\x18\x06 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x07 \x01(\x01\"l\n\x0bProductView\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x10\n\x08referrer\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x05 \x01(\t\"p\n\rSearchRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05query\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0c\n\x04page\x18\x04 \x01(\x05\x12\r\n\x05limit\x18\x05 \x01(\x05\x12\x0f\n\x07\x66ilters\x18\x06 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_schemas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHIPPINGADDRESS']._serialized_start=26
  _globals['_SHIPPINGADDRESS']._serialized_end=111
  _globals['_ORDERITEM']._serialized_start=113
  _globals['_ORDERITEM']._serialized_end=177
  _globals['_ORDER']._serialized_start=180
  _globals['_ORDER']._serialized_end=366
  _globals['_PRODUCTVIEW']._serialized_start=368
  _globals['_PRODUCTVIEW']._serialized_end=476
  _globals['_SEARCHREQUEST']._serialized_start=478
  _globals['_SEARCHREQUEST']._serialized_end=590
# @@protoc_insertion_point(module_scope)
